// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/myobject.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 3979214109799406409),
      name: 'MyObject',
      lastPropertyId: const obx_int.IdUid(5, 4501201110882340687),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6123165521011918118),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1944853320919181679),
            name: 'arraysJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3050771760860819526),
            name: 'videoName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4501201110882340687),
            name: 'datetime',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 3979214109799406409),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [6856408798996725792, 1019423933153152073],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        8996316769080108416,
        8635133340133446703,
        1934936828438333744,
        8899220560531407345,
        3106638358620180122,
        4965262473697983030
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    MyObject: obx_int.EntityDefinition<MyObject>(
        model: _entities[0],
        toOneRelations: (MyObject object) => [],
        toManyRelations: (MyObject object) => {},
        getId: (MyObject object) => object.id,
        setId: (MyObject object, int id) {
          object.id = id;
        },
        objectToFB: (MyObject object, fb.Builder fbb) {
          final arraysJsonOffset = object.arraysJson == null
              ? null
              : fbb.writeString(object.arraysJson!);
          final videoNameOffset = object.videoName == null
              ? null
              : fbb.writeString(object.videoName!);
          final datetimeOffset = object.datetime == null
              ? null
              : fbb.writeString(object.datetime!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(2, arraysJsonOffset);
          fbb.addOffset(3, videoNameOffset);
          fbb.addOffset(4, datetimeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MyObject()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..arraysJson = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 8)
            ..videoName = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 10)
            ..datetime = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 12);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MyObject] entity fields to define ObjectBox queries.
class MyObject_ {
  /// See [MyObject.id].
  static final id =
      obx.QueryIntegerProperty<MyObject>(_entities[0].properties[0]);

  /// See [MyObject.arraysJson].
  static final arraysJson =
      obx.QueryStringProperty<MyObject>(_entities[0].properties[1]);

  /// See [MyObject.videoName].
  static final videoName =
      obx.QueryStringProperty<MyObject>(_entities[0].properties[2]);

  /// See [MyObject.datetime].
  static final datetime =
      obx.QueryStringProperty<MyObject>(_entities[0].properties[3]);
}
